version: "1.0"

services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=bankapp
    ports:
      - 5431:5432
    volumes:
      - volume_name:/var/lib/postgresql/data

volumes:
  volume_name:
    name: volume_name